### ISSUE TITLE
Game hang/not responding after 5 or 10 minutes

### ISSUE THREAD

**Issue by frusio** [Sporif/dxvk-async#11]
Hello Sporif

I have an issue where the game i played freezing after logging in into the game after around 5 or 10 minutes. The dxvk-async worked fine until yesterday. So after i checked the exefile64_d3d9.log, the line ended with this error;

 err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_OUT_OF_DEVICE_MEMORY

I'm using latest Windows 10, and latest AMD driver. Running an RX 560 2GB.

Any kind of help is greatly appreciated. Thank you.

**Comment by Sporif** [comment]
Have you tried reproducing the issue with stock dxvk?

**Comment by frusio** [comment]
Tried already. the vanilla has no issue. I dont Even delete or replace the cache, the game is fine.
