### ISSUE TITLE
GTA 4 flickering dots using DXVK 1.9 on AMD RDNA2

### ISSUE THREAD

**Issue by Fezzy976** [Sporif/dxvk-async#19]
Issues using latest DXVK 1.9 with AMD 6800XT and GTA 4. Producing flickering coloured crosshairs on screen when smoke or bloom effects are used/switched. Flicker happens for a split second so capturing this was tricky.

Drivers used are 20.6.1, 20.6.2, 20.7.1, and UWP drivers. All exhibit the same issue, the issue is not present when using DX. GPU is not overclocked either and no overheating has been monitored. No other game tested or played with either DXVK or standard .API's displays this issue.

Posting this in hopes it can be fixed, as I doubt AMD will provide fixes for a DXVK issue.

Screenshots of issue.
![GTA 1](https://user-images.githubusercontent.com/87862595/126785305-eefbbc52-65bb-4a23-9759-ef593aa1870d.jpg)
![GTA 2](https://user-images.githubusercontent.com/87862595/126785310-5786472a-8fa8-4f5f-8c2e-5988731cb02f.jpg)

**Comment by Sporif** [comment]
Did you test with both stock dxvk and dxvk-async? Because if it's a general issue with dxvk this isn't the right repo.

**Comment by Fezzy976** [comment]
> Did you test with both stock dxvk and dxvk-async? Because if it's a general issue with dxvk this isn't the right repo.

yes tested with both dxvk and dxvk async

**Comment by Sporif** [comment]
And the issue occurred only with dxvk-async?

**Comment by Fezzy976** [comment]
No it occurs with both.

It seems to be more apparent the higher the resolution. It happens mainly around light or smoke sources when turning the camera.

Like I said DirectX is not effected but obviously performance is awful.

I have found a sweet spot. 2560x1440 144Hz no FPS cap and the issue whilst still there it barely appears or is noticeable. If I cap the FPS to 60fps with RTSS it becomes more apparent.

I tested out 5k144Hz using AMDs VSR and its a mess with flickering everywhere.

No other games I've played are effected.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Sporif** [comment]
> No it occurs with both.

Then since this not dxvk-async specific, please open an issue in the main dxvk repo (or search for a similar one there):

https://github.com/doitsujin/dxvk
