### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by rejedai** [Sporif/dxvk-async#2]
It would be nice to add instructions for using the patch.

**Comment by qdevpl** [comment]
You just need to clone this repository along with DXVK one, perform git apply using patch file from this one (https://git-scm.com/docs/git-apply) and then follow build instructions from DXVK https://github.com/doitsujin/dxvk#build-instructions

**Comment by rejedai** [comment]
Thank you for quick answer.

**Comment by rejedai** [comment]
Patch doesn't work for 1.7.1.

```bash
[rejedai@rj-pc dxvk-1.7.1]$ git apply /home/rejedai/Games/dxvk-1.7.1/dxvk-async.patch 
error: patch failed: src/dxvk/dxvk_context.h:1159
error: src/dxvk/dxvk_context.h: patch does not apply
```

Tested for 1.6.1, works great.

**Comment by Sporif** [comment]
You can now just use the latest patched release binaries.

https://github.com/Sporif/dxvk-async/releases/tag/1.7.2
