### ISSUE TITLE
No DX12 with 1.9.1

### ISSUE THREAD

**Issue by jarrard** [Sporif/dxvk-async#23]
Been testing this with Lutris and I noticed when using this version of dxvk there is no dx12 option in games. The lutris 191L version however works.

**Comment by jarrard** [comment]
Figured it out, your missing d3d12.dll

**Comment by Ryusennin** [comment]
d3d12.dll is provided by vkd3d, not dxvk.

**Comment by jarrard** [comment]
yep, I was a little confused and thought it was packaged together. Only proton does that.
