### ISSUE TITLE
Dxvk-async forces GW2 into fullscreen mode

### ISSUE THREAD

**Issue by kazerniel** [Sporif/dxvk-async#24]
Even if in the ingame options windowed fullscreen is selected, the game behaves as if it was in fullscreen (less smooth alt+tabbing, f.lux overlay hides the cursor like it does with fullscreen games).

I run it on Win10 via the GW2 Addon Manager.

**Comment by Ryusennin** [comment]
Report bugs to the original team: https://github.com/doitsujin/dxvk
