### ISSUE TITLE
Patch doesn't work for 1.7.1.

### ISSUE THREAD

**Issue by rejedai** [Sporif/dxvk-async#3]
```bash
[rejedai@rj-pc dxvk-1.7.1]$ git apply /home/rejedai/Games/dxvk-1.7.1/dxvk-async.patch 
error: patch failed: src/dxvk/dxvk_context.h:1159
error: src/dxvk/dxvk_context.h: patch does not apply
```

Tested for 1.6.1, works great.

_Originally posted by @rejedai in https://github.com/Sporif/dxvk-async/issues/2#issuecomment-675025517_

**Comment by Sporif** [comment]
Use the `patch` command, i.e  `patch -Np1 -i dxvk-async.patch` instead. 

`git apply` seems to only work with a perfect patch.

**Comment by rejedai** [comment]
Perfect. Thank you.
