### ISSUE TITLE
DXVK-Async interaction with anti cheats

### ISSUE THREAD

**Issue by orowith2os** [Sporif/dxvk-async#42]
There's been some stuff about using dxvk-async on multiplayer games and getting banned for it, some people say that this has been fixed. Is this true? Is it still a risk? 
Would the answer to this be able to be included in the README to address this question in the future?

**Comment by Sporif** [comment]
I've never seen anyone banned specifically for using dxvk-async. For me personally I've used it with no issues in plenty of multiplayer games with all kind of anticheats. But that that doesn't mean any game developer couldn't easily start banning people if they wanted to. So it's low risk, but not non-zero. Also I feel dxvk-async's relative lack of popularity has contributed a huge part to why it hasn't been banned.

If you think something like this should be in the README feel free to open a pull request.

**Comment by orowith2os** [comment]
I'll leave this issue to be as a tally for how many people have been banned because of using dxvk-async on a game with an anti cheat, if you don't mind. That way we can see if anybody is still getting banned because of it.

**Comment by Elendil211** [comment]
This is probably about this report on reddit: https://www.reddit.com/r/linux_gaming/comments/9fkuq9/overwatch_avoid_async_option_for_dxvk_banned_for/

The person who created it, later edited the post, mentioning that other people who were not using DXVK_ASYNC were also banned. Later, Blizzard apologized for the bans, saying that they were due an error, and everyone was unbanned.

**Comment by Eugevin** [comment]
Using DXVK_ASYNC just about one year and no issues has been founded. Playing many online game, such as Apex, Overwatch, GTA 5, Fall Guys and some other multiplayer games - no bans, no warning about soon bans, etc.

I think that problem described in reddit theme from link above, is exclusive blizzard issue (maybe they're using some of theirs shit-quality unique propietary anti-cheat software and it triggers on async dxvk) , but async DXVK **absolutely has no affect** to other games.

**Comment by Bitwolfies** [comment]
From what I recall, the original async patch that was merged into mainline (not this one) was poorly put together and merged without any real testing, causing the bans on seemingly *just* overwatch. All of which were reversed. 

Naturally, it was pulled because you don't want your userbase getting banned cause of you, even if you claim you're not at fault in the project readme. Even more so when your project is now being used by the biggest pc gaming store and is gonna be shipped in a retail console.

Supposedly this patch fixed what threw off the anti cheat and things have been smooth, but i'm sure the devs are now extra wary of trying to add async again, even if its benefits are massive and could even obsolete steams shader downloads in some regards.

Someone on reddit claimed this patch wont be needed anymore after 1.11, anyone know anything about that? Are they gonna try merging it again? I found nothing on the git. https://www.reddit.com/r/linux_gaming/comments/whjlcy/what_does_env_variable_gl_dxvk_optimizations_do/ij67xic/?context=3

**Comment by orowith2os** [comment]
> Someone on reddit claimed this patch wont be needed anymore after 1.11, anyone know anything about that? Are they gonna try merging it again? I found nothing on the git. https://www.reddit.com/r/linux_gaming/comments/whjlcy/what_does_env_variable_gl_dxvk_optimizations_do/ij67xic/?context=3

I believe this is due to the RADV driver having asynchronous compiling enabled by default, don't quote me on that. I'll see if I can dig up anything on it.

**Comment by orowith2os** [comment]
Turns out that it was because dxvk can partially make shaders during loading screens now (used to be ignored), now it's on Mesa to implement the features required. From what I can tell, bare DXVK is still inferior without the patch, but it's catching up. Feel free to correct me if I'm wrong, Sporif.

**Comment by Sporif** [comment]
> Turns out that it was because dxvk can partially make shaders during loading screens now (used to be ignored), now it's on Mesa to implement the features required. From what I can tell, bare DXVK is still inferior without the patch, but it's catching up. Feel free to correct me if I'm wrong, Sporif.

DXVK master with the latest nvidia vulkan driver is pretty damn good. There is still some initial stutter for a few seconds, the first time you play a game. But after that, even different areas/maps don't seem to introduce stutter. I've tested it out on Witcher 3, Overwatch, BF1 and BFV and didn't miss async at all.

**Comment by orowith2os** [comment]
Can we expect this patch to be obsolete once the AMD and Intel drivers have the required components implemented? Or will it be able to be used alongside the new DXVK versions?

**Comment by Sporif** [comment]
> Can we expect this patch to be obsolete once the AMD and Intel drivers have the required components implemented? Or will it be able to be used alongside the new DXVK versions?

Well the patch will still work, but it will disable said dxvk feature

**Comment by orowith2os** [comment]
I'll close this issue, since it seems that nobody has any problems with async on multiplayer games, and it might be a useless issue anyways, if newer versions of DXVK are going to potentially replace it (with a few rare use cases). Will reopen if anybody feels it should stay open.

**Comment by Bitwolfies** [comment]
> Turns out that it was because dxvk can partially make shaders during loading screens now (used to be ignored), now it's on Mesa to implement the features required. From what I can tell, bare DXVK is still inferior without the patch, but it's catching up. Feel free to correct me if I'm wrong, Sporif.

Was this something that NV/Mesa built for DXVK? Or just something it was able to take advantage of?

**Comment by orowith2os** [comment]
I think the issue was that dxvk used to not be able to make partial shader caches, and now, assuming the required Vulkan extensions are there, it can make them (that's what the loading screen on Windows games does). I'm not sure on the specifics, but that seems to be how it works.
