### ISSUE TITLE
DXVK 1.10.2 released!

### ISSUE THREAD

**Issue by runboy93** [Sporif/dxvk-async#44]
@Sporif 

https://github.com/doitsujin/dxvk/releases/tag/v1.10.2

**Comment by jarrard** [comment]
cool

**Comment by Sporif** [comment]
OK, I just realized that 1.10.2 is from a different branch than master and doesn't require a new patch ([dxvk-async-af418dc.patch](https://github.com/Sporif/dxvk-async/commit/afa870972ac7cd2a48787f76503acc10533228b4#diff-adcb2aa19cfad152b7a9334e7e898a9c3a9ef96f764de489fbc2b661da98984d) still works for the 1.10.x branch). I've uploaded a release for that version first. This means my comment above is not relevant to this issue, but I still plan to release the updated patch.

**Comment by ms178** [comment]
@Sporif The new 1.10.2 doesn't seem to apply cleanly on 1.10.2 vanilla though:

```
==> Beginning prepare()...
patching file meson.build
patching file src/dxvk/dxvk_context.cpp
Hunk #1 FAILED at 4187.
Hunk #2 succeeded at 4379 (offset -81 lines).
Hunk #3 succeeded at 4401 (offset -81 lines).
Hunk #4 succeeded at 4809 (offset -74 lines).
Hunk #5 succeeded at 5223 (offset -91 lines).
1 out of 5 hunks FAILED -- saving rejects to file src/dxvk/dxvk_context.cpp.rej
patching file src/dxvk/dxvk_context.h
Hunk #1 succeeded at 1227 (offset -12 lines).
Hunk #2 succeeded at 1307 (offset -12 lines).
patching file src/dxvk/dxvk_graphics.cpp
Hunk #1 succeeded at 62 (offset 12 lines).
Hunk #2 succeeded at 72 (offset 12 lines).
Hunk #3 succeeded at 115 (offset 12 lines).
Hunk #4 succeeded at 124 (offset 12 lines).
patching file src/dxvk/dxvk_graphics.h
Hunk #1 succeeded at 199 (offset -1 lines).
Hunk #2 succeeded at 214 (offset -1 lines).
Hunk #3 succeeded at 243 (offset 1 line).
Hunk #4 succeeded at 273 (offset 1 line).
patching file src/dxvk/dxvk_image.h
patching file src/dxvk/dxvk_options.cpp
patching file src/dxvk/dxvk_options.h
patching file src/dxvk/dxvk_pipecompiler.cpp
patching file src/dxvk/dxvk_pipecompiler.h
patching file src/dxvk/dxvk_pipemanager.cpp
patching file src/dxvk/dxvk_pipemanager.h
patching file src/dxvk/meson.build
```

**Comment by Sporif** [comment]
The latest [dxvk-async.patch](https://github.com/Sporif/dxvk-async/blob/master/dxvk-async.patch) doesn't work with 1.10.2, but [dxvk-async-af418dc.patch](https://github.com/Sporif/dxvk-async/blob/master/dxvk-async-af418dc.patch) does. I should probably update the README with a table explaining which patch is compatible with which dxvk version.

**Comment by Sporif** [comment]
Your patch file is wrong, it's missing spaces in various lines. Download the patch from this link [dxvk-async-af418dc.patch](https://raw.githubusercontent.com/Sporif/dxvk-async/master/dxvk-async-af418dc.patch) (Right Click -> Save Page or CTRL+S)

**Comment by ms178** [comment]
Thanks a lot! That solved the problem.

**Comment by loathingKernel** [comment]
Wouldn't it be more comprehensible for the `1.10.2` tag to be on commit `1111b69eb983277d7d50a507370abe77ff6a8e4e`?

**Comment by Sporif** [comment]
> Wouldn't it be more comprehensible for the `1.10.2` tag to be on commit [1111b69](https://github.com/Sporif/dxvk-async/commit/1111b69eb983277d7d50a507370abe77ff6a8e4e)?

Yeah you're right but tbh I only make those releases to share built dxvk-async, the tags are just a side effect.

**Comment by Sporif** [comment]
> Your quote/sentence is linked to the actual DXVK version, I mean for next (future) DXVK version 1.10.3 or 1.11.
> 
> I heard/read it from somebody, who believes the feature "VK_EXT_pipeline_creation_cache_control" in the next (future) DXVK version should be solve all lags by cache creation, so no async patch is needed anymore.
> 
> Best regards

No, my comment was about dxvk master, I've tried that feature and currently on my gtx 1080 with the latest vulkan beta drivers it doesn't completely solve the stuttering.
