### ISSUE TITLE
turning DXVK_ASYNC on disables keyboard input in overwatch

### ISSUE THREAD

**Issue by iBloodLust** [Sporif/dxvk-async#47]
Linux 5.19-TKG-BMQ,Tested with Wine-GE-Proton 22 and 23,
the latest DXVK 1.10.2 with the async patch. I am running the game through gamescope/.

I am able to move my mouse and interact with the game as far as menus, but the game accepts NO keyboard input. Regardless of whether the option is on or off, yes the battle.net client itself lets me type.

**Comment by Sporif** [comment]
Did you check if this occurs with an unpatched dxvk?

**Comment by GloriousEggroll** [comment]
also try not using gamescope. it's a common issue for gamescope to lock out input from various devices.

There is also an undocumented '-e' option you can try with gamescope for exclusive mode.
