### ISSUE TITLE
patch latest dxvk builds

### ISSUE THREAD

**Issue by adolfotregosa** [Sporif/dxvk-async#48]
Hi, it seams your dxvk-async patch is no longer valid from commit 8d72b8e jully 30 upwards. 

Can you have a look ?

**Comment by Sporif** [comment]
Are you saying the patch doesn't apply? Because the [latest one](https://github.com/Sporif/dxvk-async/blob/master/dxvk-async.patch) absolutely does. I just patched and built dxvk master and tested both async enabled and disabled. It still works fine.

**Comment by adolfotregosa** [comment]
> Are you saying the patch doesn't apply? Because the [latest one](https://github.com/Sporif/dxvk-async/blob/master/dxvk-async.patch) absolutely does. I just patched and built dxvk master and tested both async enabled and disabled. It still works fine.

what am i doing wrong then ?

**Comment by Sporif** [comment]
It looks like `git apply` is too strict. Try using GNU patch, e.g: `patch -Np1 -i ../dxvk/dxvk-async.patch`

**Comment by adolfotregosa** [comment]
> It looks like `git apply` is too strict. Try using GNU patch, e.g: `patch -Np1 -i ../dxvk-async/dxvk-async.patch`

Yeah, I'm still learning all this stuff so I'm sorry. It seams to work ok using patch. Thank you
