### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by niobium93** [Sporif/dxvk-async#52]
Fails with error:
```
dxvk/meson.build:119:0: ERROR: Include dir ./include/vulkan/include does not exist.
```
[Full build log and meson log.](https://gist.github.com/niobium93/f9039304e86a427d4f10a916e0b34047)

**Comment by Sporif** [comment]
This is not a dxvk-async issue, the dxvk repo now includes some git submodules. Either `git clone --recursive https://github.com/doitsujin/dxvk` for a new repo, or `git submodule update --init --recursive` for an existing one.

**Comment by niobium93** [comment]
My bad. This is a problem with the AUR package.
