### ISSUE TITLE
Trials of mana crashes when calling flammie (changing to the flying open world)

### ISSUE THREAD

**Issue by terry98** [Sporif/dxvk-async#59]
Hi, everytime I call flammie the game crashes in the loading screen. This are the last lines from the log:

err:   Exception on CS thread!
err:   DxvkCommandList: Failed to end command buffer

I'm using these settings in the dxvk.conf:
dxvk.enableAsync = true
dxvk.numAsyncThreads = 6
dxvk.enableGraphicsPipelineLibrary = true
dxvk.numCompilerThreads = 6

Also, I'm using dxvk-async 2.0 if I use 1.10.3 it plays fine, so the error is with the latest version only.

my specs

Win 10 21H2
Ryzen 7 5800x 3D
RX 6800

**Comment by Sporif** [comment]
Does this also happen with stock dxvk, or async disabled?

**Comment by terry98** [comment]
Yes, using async 2.0 with dxvk.enableAsync = false or stock doitsujin/dxvk also happens.

**Comment by Sporif** [comment]
Then it's not an issue specific to dxvk async. You should instead open an issue in doitsujin/dxvk.

**Comment by terry98** [comment]
this have been fixed in the latest master here

https://github.com/doitsujin/dxvk/actions/runs/3736849094
