### ISSUE TITLE
Patch fails to apply with current dxvk master.

### ISSUE THREAD

**Issue by TheGreatMcPain** [Sporif/dxvk-async#6]
The patch fails to apply with [this commit.](https://github.com/doitsujin/dxvk/commit/2405e474e5a102327d2e33e7c18ae160c720c23e)

The files `src/dxvk/dxvk_options.cpp` and `src/dxvk/dxvk_options.h` are the
only ones that fail.

**Comment by Sporif** [comment]
Thanks for letting me know, I updated it with a fix.
