### ISSUE TITLE
How to patch dxvk with dxvk-async.patch?

### ISSUE THREAD

**Issue by noelcurray** [Sporif/dxvk-async#65]
Hi. 

I'm trying to do dxvk-async manually. Mostly I just follow the instruction to use proton-ge-custom-bin and add DXVK_ASYNC=1 on steam but now, I try to implement this on wine gaming.

Hows to do the process of patching? Is this just copy/pasting?

**Comment by Kaptime** [comment]
The patch should work with the version it matches, it automates those changes to the source files. The most recent version of the patch supports dxvk 2.0, copy the patch file into the dxvk (2.0) directory and then open a terminal to this directory and type: git apply dxvk-async.patch
