### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by johncaling40** [Sporif/dxvk-async#7]
To install this do i just clone it and run `sudo patch`? Also how long should the patching take?

**Comment by SveSop** [comment]
No.
You download DXVK source from [https://github.com/doitsujin/dxvk](https://github.com/doitsujin/dxvk) - eg. `git clone https://github.com/doitsujin/dxvk.git dxvk`, then you clone this repo - eg, `git clone https://github.com/Sporif/dxvk-async.git async`

You will then have 2 folders in the folder you are - dxvk and async.

```
cd dxvk
patch -p1 < ../async/dxvk-async.patch
```
Then you build DXVK as described on the dxvk wiki and readme :)

**Comment by johncaling40** [comment]
> No.
> You download DXVK source from https://github.com/doitsujin/dxvk - eg. `git clone https://github.com/doitsujin/dxvk.git dxvk`, then you clone this repo - eg, `git clone https://github.com/Sporif/dxvk-async.git async`
> 
> You will then have 2 folders in the folder you are - dxvk and async.
> 
> ```
> cd dxvk
> patch -p1 < ../async/dxvk-async.patch
> ```
> 
> Then you build DXVK as described on the dxvk wiki and readme :)

OK. How do i install mingw headers 8 for ubuntu/pop 20.10

**Comment by SveSop** [comment]
You have 2 options:
1. Install from a PPA : [https://launchpad.net/~cybermax-dexter/+archive/ubuntu/mingw-w64-backport](https://launchpad.net/~cybermax-dexter/+archive/ubuntu/mingw-w64-backport)
2. Use Docker to build DXVK

Tbh, there seems to be some difficulties building newer DXVK with Ubuntu these days.. sometimes it works fine, sometimes not. The DXVK sources are mainly developed and compiled/tested on Archlinux if i am correct. (Probably preferred platform for the developers to use Archlinux).

I am sorry, but i do not have time to writeup a howto for running docker on Ubuntu atm. Google how to set up docker, and how to build a archlinux image. You would need the requirements for DXVK to build - Meson, Git, MingW and so on. It does seem to work the best once you pass the hurdle of setting it up. Running "unoficial patches" like this Async patch is not for the faint of heart. :)
