### ISSUE TITLE
What driver is need at Win10 for Quake Campions?

### ISSUE THREAD

**Issue by 12sunflowers** [Sporif/dxvk-async#70]
At Adrenaline 21.12.1, rx580
i have "Your video card or driver not support DirectX11"
![QC dxvk async](https://github.com/Sporif/dxvk-async/assets/2568511/d9aafd69-b934-408c-98e7-9b03dc401c9c)

**Comment by Ryusennin** [comment]
Your driver is probably too old. DXVK requires recent Vulkan extensions.
Try the latest Radeon version (23.4.3) which supports your GPU.

**Comment by 12sunflowers** [comment]
Thanks for reply)
23.4.3 have issues on Polaris GPUs with AMDRSServ 
that why i am still use 21.12.1

Also i have issues with original DXVK 2.0 on 21.12.1 driver

So problem is at old graphic driver?

**Comment by 12sunflowers** [comment]
Confirm
with 23.4.3 driver dxvk-async working good!
Thanks!
