### ISSUE TITLE
Gw2 and Tera online, DXVK ASYNC 1.8 & standard 1.8 not working in Windows 10

### ISSUE THREAD

**Issue by seanmacky** [Sporif/dxvk-async#8]
Hi Sporif :) 

1.7.3 was working great on Windows with Guild Wars 2. 

The new version 1.8 does not work, I start the gw2 client and then it black screens then the game just closes. No crash dump is generated though ...

I mentioned it on the DXVK discord channel and Joshie ( creator of d9vk ) said the DXVK Async Patch might need to be rebased for the new DXVK version 1.8 ?

I've tried with different drivers ( AMD - using rx 5700xt )

Using latest Windows 10 build.

I have friends using the 1.8 Async build in Linux and it's working fine there with GW2 so the issue only seems to be in Windows with this version .

Any suggestions ? 

Thank you

**Comment by EmaProwler** [comment]
I have the same problem in the game TERA just starts it quits. with the version of dxvk 1.8 async but I also tried the original version and the same thing happens to me.
any ideas ?

**Comment by Sporif** [comment]
@seanmacky Does dxvk v1.8 without async work?

**Comment by seanmacky** [comment]
> 
> 
> @seanmacky Does dxvk v1.8 without async work?

I just tested. It's also happening with standard 1.8 :(

**Comment by Ryusennin** [comment]
Please change the title to specifically mention Guild Wars.

dxvk 1.8 (standard and async) definitely works on both Win7 and Win10.

**Comment by seanmacky** [comment]
> I just tested AC Origins and Odyssey, dxvk 1.8 (standard and async) definitely works on both Win7 and Win10.
> 
> Please change the misleading title to specifically mention Guild Wars 2.

No worries updated 👌

**Comment by Sporif** [comment]
@seanmacky So if this is not a async specific issue, we can close this no?

**Comment by seanmacky** [comment]
> 
> 
> @seanmacky So if this is not a async specific issue, we can close this no?

Hi Sporif. I spoke with Joshie and doitsujin and it turns out 1.8 release had a regression that had a derpy regression that breaks some d3d9 games.

DXVK Master is working - i tried that on their recommendation :) @EmaProwler 

@Sporif  or someone - are you able to patch current DXVK Master so i can access the built dll's ?

Thanks for your help everyone

**Comment by EmaProwler** [comment]
@seanmacky I really don't know what you mean by "master" I tried 1.8 without async, I mean the original and the patched version and none worked for me and TERA uses direct x 11 at 64bits

**Comment by Sporif** [comment]
@seanmacky @EmaProwler Here is the latest dxvk commit with just the async patch:
[dxvk-async-1.8_13_g5e55ced8.tar.gz](https://github.com/Sporif/dxvk-async/files/6027793/dxvk-async-1.8_13_g5e55ced8.tar.gz)

**Comment by seanmacky** [comment]
> 
> 
> @seanmacky @EmaProwler Here is the latest dxvk commit with just the async patch:
> [dxvk-async-1.8_13_g5e55ced8.tar.gz](https://github.com/Sporif/dxvk-async/files/6027793/dxvk-async-1.8_13_g5e55ced8.tar.gz)

Thanks Sporif - works perfectly !
